# Generated by Django 5.2.8 on 2025-11-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
        ('api', '0002_material_upldate_section_batch_alter_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secadmin',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api.section'),
        ),
    ]
