# Generated by Django 5.2.8 on 2025-11-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_alter_secadmin_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secadmin',
            name='section',
            field=models.CharField(max_length=40),
        ),
    ]
